### ISSUE TITLE
Is the restriction on R version necessary?

### ISSUE THREAD

**Issue by privefl** [hendriau/Summix#7]
I have only R 3.6.1 on the server I'm working on.
It seems I can download the source code, modify the current restriction R >= 4.1 (to e.g. R >= 3.6), and the package still works.
So, is this really needed?

**Comment by hendriau** [comment]
Hi Florian,

Thanks for your interest in Summix.  I believe the 4.1 requirement was for approval from bioconductor. Glad you were able to find a work around.

Best
Audrey

Sent from my iPhone

On Mar 23, 2022, at 8:59 AM, Florian Privé ***@***.***> wrote:

﻿
[External Email - Use Caution]

I have only R 3.6.1 on the server I'm working on.
It seems I can download the source code, modify the current restriction R >= 4.1 (to e.g. R >= 3.6), and the package still works.
So, is this really needed?

**Comment by privefl** [comment]
Publishing on CRAN could be a nice and useful alternative :')
